<!-- Web Systems and Web Computing Project Part 3
Filename: meta.inc
Description: generic meta infromation for webpages

For course: CAS 6WW3
By: Omer Waseem (graduate student) -->

<!-- Webpage meta information -->
<meta charset="UTF-8">
<meta name="author" content="Omer Waseem">
<meta name="description" content="Search and share information about hiking trails.">
<meta name="keywords" content="trails, paths, hiking, nature">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Addon 1: Android homescreen tags -->
<meta name="mobile-web-app-capable" content="yes">
<link rel="icon" sizes="128x128" href="images/favicon.png"/>

<!-- Addon 1: Apple homescreen tags -->
<link rel="apple-touch-icon" href="images/favicon.png"/>
<meta name="apple-mobile-web-appcapable" content="yes"/>

<!-- Addon 1: Twitter cards -->
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@TheHiddenPath" />
<meta name="twitter:creator" content="@OmerWaseem" />